<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PaypalController extends Controller
{
    public function index()
    {

        $clientId = "ASo11bxs9WRcqrGhFjVmvcfVaQxH9hNb7FM3LE_HH9nZp6QQ-F8gYRkGotLBP4LRRrTFlMsARvv_9sg8";
        $clientSecret = "EHZwO2qNe65FvtQIwQ7kmfkWAnJG5U8W9VO8s2maQV4y5P7CAH4EJ9Pdhg9DZ2vcxCwYBHLDhLP952CH";

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // $ch = curl_init();

        // curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/oauth2/token');
        // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        // curl_setopt($ch, CURLOPT_POST, 1);

        // $headers = array();
        // $headers[] = 'Authorization: Basic QVNvMTFieHM5V1JjcXJHaEZqVm12Y2ZWYVF4SDloTmI3Rk0zTEVfSEg5blpwNlFRLUY4Z1lSa0dvdExCUDRMUlJyVEZsTXNBUnZ2XzlzZzg6RUhad08ycU5lNjVGdnRRSXdRN2ttZmtXQW5KRzVVOFc5Vk84czJtYVFWNHk1UDdDQUg0RUo5UGRoZzlEWjJ2Y3hDd1lCSExEaExQOTUyQ0g=';
        // $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        // $result = curl_exec($ch);
        // return response()->json($result);
        // if (curl_errno($ch)) {
        //     echo 'Error:' . curl_error($ch);
        // }
        // curl_close($ch);

        $ch = curl_init();
        $clientId = "ASo11bxs9WRcqrGhFjVmvcfVaQxH9hNb7FM3LE_HH9nZp6QQ-F8gYRkGotLBP4LRRrTFlMsARvv_9sg8";
        $secret = "EHZwO2qNe65FvtQIwQ7kmfkWAnJG5U8W9VO8s2maQV4y5P7CAH4EJ9Pdhg9DZ2vcxCwYBHLDhLP952CH";

        curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/oauth2/token");
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSLVERSION, 6); //NEW ADDITION
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_USERPWD, $clientId . ":" . $secret);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials&ignoreCache=true&return_authn_schemes=true&return_client_metadata=true&return_unconsented_scopes=true");

        $result = curl_exec($ch);

        if (empty($result)) die("Error: No response.");
        else {
            $json = json_decode($result);
            print_r($json->access_token);
        }

        curl_close($ch); //THIS CODE IS NOW WORKING!
    }
}
