<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class PaypalController extends Controller
{
    public function index()
    {

        $clientId = "ASo11bxs9WRcqrGhFjVmvcfVaQxH9hNb7FM3LE_HH9nZp6QQ-F8gYRkGotLBP4LRRrTFlMsARvv_9sg8";
        $clientSecret = "EHZwO2qNe65FvtQIwQ7kmfkWAnJG5U8W9VO8s2maQV4y5P7CAH4EJ9Pdhg9DZ2vcxCwYBHLDhLP952CH";

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // $ch = curl_init();

        // curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/oauth2/token');
        // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        // curl_setopt($ch, CURLOPT_POST, 1);

        // $headers = array();
        // $headers[] = 'Authorization: Basic QVNvMTFieHM5V1JjcXJHaEZqVm12Y2ZWYVF4SDloTmI3Rk0zTEVfSEg5blpwNlFRLUY4Z1lSa0dvdExCUDRMUlJyVEZsTXNBUnZ2XzlzZzg6RUhad08ycU5lNjVGdnRRSXdRN2ttZmtXQW5KRzVVOFc5Vk84czJtYVFWNHk1UDdDQUg0RUo5UGRoZzlEWjJ2Y3hDd1lCSExEaExQOTUyQ0g=';
        // $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        // $result = curl_exec($ch);
        // return response()->json($result);
        // if (curl_errno($ch)) {
        //     echo 'Error:' . curl_error($ch);
        // }
        // curl_close($ch);

        $ch = curl_init();
        $clientId = "ASo11bxs9WRcqrGhFjVmvcfVaQxH9hNb7FM3LE_HH9nZp6QQ-F8gYRkGotLBP4LRRrTFlMsARvv_9sg8";
        $secret = "EHZwO2qNe65FvtQIwQ7kmfkWAnJG5U8W9VO8s2maQV4y5P7CAH4EJ9Pdhg9DZ2vcxCwYBHLDhLP952CH";

        curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/oauth2/token");
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSLVERSION, 6); //NEW ADDITION
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_USERPWD, $clientId . ":" . $secret);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials&ignoreCache=true&return_authn_schemes=true&return_client_metadata=true&return_unconsented_scopes=true");

        $result = curl_exec($ch);

        if (empty($result)) die("Error: No response.");
        else {
            $json = json_decode($result);
            $token = $json->access_token;
            // print_r($json->access_token);
            // dd($token);
        }

        

        curl_close($ch); //THIS CODE IS NOW WORKING!

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        
                $ch = curl_init();

                curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v2/invoicing/generate-next-invoice-number');
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($ch, CURLOPT_POST, 1);

                $headers = array();
                $headers[] = 'Authorization: Bearer '.$token;
                curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

                $result = curl_exec($ch);
                // dd($result);
                if (curl_errno($ch)) {
                    echo 'Error:' . curl_error($ch);
                }
                curl_close($ch);

                $current = Carbon::now();

                $json = '{
                    "detail": {
                        "invoice_number": "$result",
                        "invoice_date": "$current",
                        "payment_term": {
                            "term_type": "NET_10",
                            "due_date": "2023-02-14"
                        },
                        "currency_code": "USD",
                        "note": "<A note to the invoice recipient. Also appears on the invoice notification email.>"
                    },
                    "invoicer": {
                        "name": {
                            "given_name": "David",
                            "surname": "Larusso"
                        }
                    },
                    "primary_recipients": [
                        {
                            "billing_info": {
                                "name": {
                                    "given_name": "Stephanie",
                                    "surname": "Meyers"
                                },
                                "email_address": "foobuyer@example.com",
                                "additional_info_value": "add-info"
                            }
                        }
                    ],
                    "items": [
                        {
                            "name": "Yoga Mat",
                            "description": "Elastic mat to practice yoga.",
                            "quantity": "1",
                            "unit_amount": {
                                "currency_code": "USD",
                                "value": "50.00"
                            }
                        }
                    ],
                    "configuration": {
                        "partial_payment": {
                            "allow_partial_payment": true,
                            "minimum_amount_due": {
                                "currency_code": "USD",
                                "value": "20.00"
                            }
                        },
                        "allow_tip": true,
                        "tax_calculated_after_discount": true,
                        "tax_inclusive": false
                    }
                }';
                
                $php_string = json_encode($json, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
                $result = json_decode($result);

               // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
               $ch = curl_init();

               curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v2/invoicing/invoices');
               curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
               curl_setopt($ch, CURLOPT_POST, 1);
               curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n    \"detail\": {\n        \"invoice_number\": \"".rand(9,999999)."\",\n        \"invoice_date\": \"2022-02-04\",\n        \"payment_term\": {\n            \"term_type\": \"NET_10\",\n            \"due_date\": \"2022-02-14\"\n        },\n        \"currency_code\": \"USD\",\n        \"note\": \"<A note to the invoice recipient. Also appears on the invoice notification email.>\"\n    },\n    \"invoicer\": {\n        \"name\": {\n            \"given_name\": \"David\",\n            \"surname\": \"Larusso\"\n        }\n    },\n    \"primary_recipients\": [\n        {\n            \"billing_info\": {\n                \"name\": {\n                    \"given_name\": \"Stephanie\",\n                    \"surname\": \"Meyers\"\n                },\n                \"email_address\": \"foobuyer@example.com\",\n                \"additional_info_value\": \"add-info\"\n            }\n        }\n    ],\n    \"items\": [\n        {\n            \"name\": \"Yoga Mat\",\n            \"description\": \"Elastic mat to practice yoga.\",\n            \"quantity\": \"1\",\n            \"unit_amount\": {\n                \"currency_code\": \"USD\",\n                \"value\": \"50.00\"\n            }\n        }\n    ],\n    \"configuration\": {\n        \"partial_payment\": {\n            \"allow_partial_payment\": true,\n            \"minimum_amount_due\": {\n                \"currency_code\": \"USD\",\n                \"value\": \"20.00\"\n            }\n        },\n        \"allow_tip\": true,\n        \"tax_calculated_after_discount\": true,\n        \"tax_inclusive\": false\n    }\n}");
               
               $headers = array();
               $headers[] = 'Content-Type: application/json';
               $headers[] = 'Paypal-Request-Id: 88506827-6626-4b55-bca8-0e41dc12cefe';
               $headers[] = 'Prefer: return=representation';
               $headers[] = 'Authorization: Bearer A21AAJS1nopnb1tVv2Jc8rvvkNkPq3mbgWeiChNl6N4C9Rsajmb9J_QM77rflTM2d_CyjfIF_mllhFgE1MFC8JDNEClRiZKhA';
               curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
               
               $result = curl_exec($ch);
               dd($result);
               if (curl_errno($ch)) {
                   echo 'Error:' . curl_error($ch);
               }
               curl_close($ch);

                
    }
}
